"""
Comprehensive ICD-10 / CPT / Service Code database for Saudi clinics.
Covers the most common diagnoses seen in outpatient + ER settings.
"""

# ─────────────────────────────────────────────────────────────────────────────
# Structure per ICD:
#   name_ar:      Arabic description
#   name_en:      English description
#   valid_cpt:    List of valid CPT codes
#   valid_src:    Valid CCHI source codes (Saudi system)
#   forbidden_cpt: CPT codes commonly mistaken for this diagnosis
#   specificity:  "specific" | "unspecified" — unspecified should be avoided
#   prefer_code:  More specific ICD to use instead (if unspecified)
#   category:     Clinical category for grouping
#   requires_cb:  Checkboxes that MUST be ticked
# ─────────────────────────────────────────────────────────────────────────────

ICD_DATABASE = {

    # ── RESPIRATORY ──────────────────────────────────────────────────────────
    "J06.9": {
        "name_ar": "التهاب الجهاز التنفسي العلوي الحاد غير محدد",
        "name_en": "Acute upper respiratory infection, unspecified",
        "valid_cpt": ["99213","99214","99202","99203"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","71046","93000"],
        "specificity": "unspecified",
        "prefer_code": "J00 / J02.9 / J04.0",
        "category": "تنفسي",
        "requires_cb": [],
    },
    "J00": {
        "name_ar": "نزلة برد (التهاب الأنف والبلعوم الحاد)",
        "name_en": "Acute nasopharyngitis (common cold)",
        "valid_cpt": ["99213","99202","99203"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","71046"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "تنفسي",
        "requires_cb": [],
    },
    "J18.9": {
        "name_ar": "التهاب رئوي غير محدد",
        "name_en": "Pneumonia, unspecified",
        "valid_cpt": ["99213","99214","99215","71046","71045"],
        "valid_src": ["MG1001","MG1002","MG5001"],
        "forbidden_cpt": ["99232","93000","80047"],
        "specificity": "unspecified",
        "prefer_code": "J15.9 / J13 / J12.9",
        "category": "تنفسي",
        "requires_cb": [],
    },
    "J45.9": {
        "name_ar": "الربو غير محدد",
        "name_en": "Asthma, unspecified",
        "valid_cpt": ["99213","99214","94640","94664","94010"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","71046","93000"],
        "specificity": "unspecified",
        "prefer_code": "J45.20 / J45.30 / J45.40 / J45.50",
        "category": "تنفسي",
        "requires_cb": [],
    },
    "J45.5": {
        "name_ar": "الربو المستمر الشديد — بدون حالة حادة",
        "name_en": "Severe persistent asthma, uncomplicated",
        "valid_cpt": ["99213","99214","99215","94640","94664"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "تنفسي",
        "requires_cb": [],
    },
    "J45.41": {
        "name_ar": "الربو المستمر المتوسط — مع حالة حادة",
        "name_en": "Moderate persistent asthma with acute exacerbation",
        "valid_cpt": ["99213","99214","99215","94640"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "تنفسي",
        "requires_cb": [],
    },

    # ── GASTROINTESTINAL ─────────────────────────────────────────────────────
    "K29.7": {
        "name_ar": "التهاب المعدة غير محدد",
        "name_en": "Gastritis, unspecified",
        "valid_cpt": ["99213","99214"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","43239","71046"],
        "specificity": "unspecified",
        "prefer_code": "K29.70 (مع H.pylori) / K29.71 (مع نزيف)",
        "category": "هضمي",
        "requires_cb": [],
    },
    "K29.70": {
        "name_ar": "التهاب المعدة بسبب H. pylori",
        "name_en": "Gastritis due to H. pylori",
        "valid_cpt": ["99213","99214"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","43239"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "هضمي",
        "requires_cb": [],
    },
    "K21.0": {
        "name_ar": "ارتداد معدي مريئي مع التهاب المريء",
        "name_en": "GERD with oesophagitis",
        "valid_cpt": ["99213","99214","43239"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","71046"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "هضمي",
        "requires_cb": [],
    },
    "K21.9": {
        "name_ar": "ارتداد معدي مريئي بدون التهاب المريء",
        "name_en": "GERD without oesophagitis",
        "valid_cpt": ["99213","99214"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["43239"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "هضمي",
        "requires_cb": [],
    },
    "K57.30": {
        "name_ar": "داء الرتج في الأمعاء الغليظة بدون انثقاب",
        "name_en": "Diverticulosis of large intestine without perforation",
        "valid_cpt": ["99213","99214","45378"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "هضمي",
        "requires_cb": [],
    },
    "K80.20": {
        "name_ar": "حصوة في المرارة بدون التهاب المرارة",
        "name_en": "Calculus of gallbladder without cholecystitis",
        "valid_cpt": ["99213","99214","76705","47562"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "هضمي",
        "requires_cb": [],
    },

    # ── ENDOCRINE / METABOLIC ────────────────────────────────────────────────
    "E11.9": {
        "name_ar": "سكري النوع الثاني بدون مضاعفات",
        "name_en": "Type 2 diabetes without complications",
        "valid_cpt": ["99213","99214","80047","83036","82947"],
        "valid_src": ["MG1001","MG1002","MG2001"],
        "forbidden_cpt": ["99285","93000","71046"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "غدد صماء",
        "requires_cb": ["chronic"],
    },
    "E11.65": {
        "name_ar": "سكري النوع الثاني مع ضعف التحكم في الجلوكوز",
        "name_en": "Type 2 diabetes with hyperglycemia",
        "valid_cpt": ["99213","99214","99215","80047","83036"],
        "valid_src": ["MG1001","MG1002","MG2001"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "غدد صماء",
        "requires_cb": ["chronic"],
    },
    "E78.5": {
        "name_ar": "فرط شحميات الدم غير محدد",
        "name_en": "Hyperlipidemia, unspecified",
        "valid_cpt": ["99213","99214","80061","82465"],
        "valid_src": ["MG1001","MG1002","MG2001"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "E78.00 / E78.1 / E78.2",
        "category": "غدد صماء",
        "requires_cb": ["chronic"],
    },
    "E66.9": {
        "name_ar": "السمنة غير محددة",
        "name_en": "Obesity, unspecified",
        "valid_cpt": ["99213","99214","99401"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "E66.01 / E66.09",
        "category": "غدد صماء",
        "requires_cb": ["chronic"],
    },

    # ── CARDIOVASCULAR ───────────────────────────────────────────────────────
    "I10": {
        "name_ar": "ارتفاع ضغط الدم الأساسي",
        "name_en": "Essential hypertension",
        "valid_cpt": ["99213","99214","93000","93005"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["99285","71046","80047"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "قلب وأوعية",
        "requires_cb": ["chronic"],
    },
    "I25.10": {
        "name_ar": "مرض القلب الإقفاري المزمن بدون ذبحة صدرية",
        "name_en": "Atherosclerotic heart disease without angina",
        "valid_cpt": ["99213","99214","99215","93000","93306"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "قلب وأوعية",
        "requires_cb": ["chronic"],
    },
    "I48.91": {
        "name_ar": "الرجفان الأذيني غير محدد",
        "name_en": "Unspecified atrial fibrillation",
        "valid_cpt": ["99213","99214","99215","93000","93224"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "I48.0 / I48.11 / I48.19",
        "category": "قلب وأوعية",
        "requires_cb": ["chronic"],
    },

    # ── MUSCULOSKELETAL ──────────────────────────────────────────────────────
    "M54.5": {
        "name_ar": "ألم أسفل الظهر",
        "name_en": "Low back pain",
        "valid_cpt": ["99213","99214","72148","72052","97110","97012"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["93000","80047"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "عظام ومفاصل",
        "requires_cb": [],
    },
    "M79.3": {
        "name_ar": "داء النسيج الضام (التليف العضلي)",
        "name_en": "Panniculitis",
        "valid_cpt": ["99213","99214"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "عظام ومفاصل",
        "requires_cb": [],
    },
    "M17.9": {
        "name_ar": "التهاب مفصل الركبة غير محدد",
        "name_en": "Osteoarthritis of knee, unspecified",
        "valid_cpt": ["99213","99214","73562","73564","97110"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "M17.11 / M17.12 (أيمن/أيسر)",
        "category": "عظام ومفاصل",
        "requires_cb": ["chronic"],
    },
    "M25.561": {
        "name_ar": "ألم مفصل الكتف الأيمن",
        "name_en": "Pain in right shoulder",
        "valid_cpt": ["99213","99214","73221","97110"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "عظام ومفاصل",
        "requires_cb": [],
    },

    # ── GENITOURINARY / OBSTETRICS ───────────────────────────────────────────
    "N97.0": {
        "name_ar": "عقم أنثوي ناتج عن عدم الإباضة",
        "name_en": "Female infertility due to anovulation",
        "valid_cpt": ["99213","99214","99215","58150"],
        "valid_src": ["MG1001","MG2022","MG2031"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "نساء وولادة",
        "requires_cb": ["infertility","pregnancy"],
    },
    "N39.0": {
        "name_ar": "التهاب المسالك البولية غير محدد الموقع",
        "name_en": "Urinary tract infection, site not specified",
        "valid_cpt": ["99213","99214","81001","81003","87086"],
        "valid_src": ["MG1001","MG1002","MG2001"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "بولي",
        "requires_cb": [],
    },
    "O26.89": {
        "name_ar": "حالات أخرى محددة مرتبطة بالحمل",
        "name_en": "Other specified pregnancy-related conditions",
        "valid_cpt": ["99213","99214","76801","76805"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "نساء وولادة",
        "requires_cb": ["pregnancy"],
    },

    # ── NEUROLOGY / PSYCHIATRY ───────────────────────────────────────────────
    "G43.909": {
        "name_ar": "الصداع النصفي غير محدد بدون حالة حادة",
        "name_en": "Migraine, unspecified, not intractable",
        "valid_cpt": ["99213","99214","70553"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": ["93000"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "أعصاب",
        "requires_cb": [],
    },
    "F41.1": {
        "name_ar": "اضطراب القلق المعمم",
        "name_en": "Generalized anxiety disorder",
        "valid_cpt": ["99213","99214","99215","90837","90834"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "specific",
        "prefer_code": None,
        "category": "نفسي",
        "requires_cb": ["psychiatric"],
    },
    "F32.9": {
        "name_ar": "نوبة الاكتئاب غير محددة",
        "name_en": "Major depressive disorder, unspecified",
        "valid_cpt": ["99213","99214","99215","90837"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "F32.0 / F32.1 / F32.2",
        "category": "نفسي",
        "requires_cb": ["psychiatric"],
    },

    # ── DERMATOLOGY ──────────────────────────────────────────────────────────
    "L20.9": {
        "name_ar": "الأكزيما التأتبية غير محددة",
        "name_en": "Atopic dermatitis, unspecified",
        "valid_cpt": ["99213","99214"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "L20.0 / L20.81 / L20.82",
        "category": "جلدية",
        "requires_cb": [],
    },
    "L50.9": {
        "name_ar": "الشرى غير محدد",
        "name_en": "Urticaria, unspecified",
        "valid_cpt": ["99213","99214"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "L50.0 (تحسسي) / L50.1 (خلوي)",
        "category": "جلدية",
        "requires_cb": [],
    },

    # ── ENT ───────────────────────────────────────────────────────────────────
    "H66.90": {
        "name_ar": "التهاب الأذن الوسطى القيحي غير محدد",
        "name_en": "Otitis media, unspecified",
        "valid_cpt": ["99213","99214","92552"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "H66.001 / H66.011 (أيمن/أيسر)",
        "category": "أنف وأذن وحنجرة",
        "requires_cb": [],
    },
    "J32.9": {
        "name_ar": "التهاب الجيوب الأنفية المزمن غير محدد",
        "name_en": "Chronic sinusitis, unspecified",
        "valid_cpt": ["99213","99214","70486"],
        "valid_src": ["MG1001","MG1002"],
        "forbidden_cpt": [],
        "specificity": "unspecified",
        "prefer_code": "J32.0 / J32.1 / J32.2 (حسب الجيب المصاب)",
        "category": "أنف وأذن وحنجرة",
        "requires_cb": [],
    },

    # ── PREVENTIVE / CHECK-UP ────────────────────────────────────────────────
    "Z00.00": {
        "name_ar": "فحص طبي دوري شامل بدون نتائج شاذة",
        "name_en": "Encounter for general adult medical exam without abnormal findings",
        "valid_cpt": ["99395","99396","99397"],
        "valid_src": ["MG1001"],
        "forbidden_cpt": ["99213","99214","99285"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "وقائي",
        "requires_cb": [],
    },
    "Z00.01": {
        "name_ar": "فحص طبي دوري شامل مع نتائج شاذة",
        "name_en": "Encounter for general adult medical exam with abnormal findings",
        "valid_cpt": ["99395","99396","99397"],
        "valid_src": ["MG1001"],
        "forbidden_cpt": ["99213","99285"],
        "specificity": "specific",
        "prefer_code": None,
        "category": "وقائي",
        "requires_cb": [],
    },

    # ── SYMPTOMS (must NOT be primary) ───────────────────────────────────────
    "R11": {
        "name_ar": "غثيان وقيء",
        "name_en": "Nausea and vomiting",
        "valid_cpt": [],
        "valid_src": [],
        "forbidden_cpt": [],
        "specificity": "symptom",
        "prefer_code": "استخدم التشخيص السببي أولاً (K29.x / K21.x / J18.9 ...)",
        "category": "أعراض — لا يُستخدم كتشخيص رئيسي",
        "requires_cb": [],
    },
    "R51": {
        "name_ar": "صداع",
        "name_en": "Headache",
        "valid_cpt": [],
        "valid_src": [],
        "forbidden_cpt": [],
        "specificity": "symptom",
        "prefer_code": "G43.x (صداع نصفي) / G44.x / R51.9",
        "category": "أعراض — لا يُستخدم كتشخيص رئيسي",
        "requires_cb": [],
    },
    "R50.9": {
        "name_ar": "حمى غير محددة",
        "name_en": "Fever, unspecified",
        "valid_cpt": [],
        "valid_src": [],
        "forbidden_cpt": [],
        "specificity": "symptom",
        "prefer_code": "J18.9 / J06.9 / A09 / B34.9 ...",
        "category": "أعراض — لا يُستخدم كتشخيص رئيسي",
        "requires_cb": [],
    },
    "R10.9": {
        "name_ar": "ألم بطني غير محدد",
        "name_en": "Unspecified abdominal pain",
        "valid_cpt": [],
        "valid_src": [],
        "forbidden_cpt": [],
        "specificity": "symptom",
        "prefer_code": "K29.x / K80.x / K35.x / N39.0 ...",
        "category": "أعراض — لا يُستخدم كتشخيص رئيسي",
        "requires_cb": [],
    },
    "R06.0": {
        "name_ar": "ضيق التنفس",
        "name_en": "Dyspnoea",
        "valid_cpt": [],
        "valid_src": [],
        "forbidden_cpt": [],
        "specificity": "symptom",
        "prefer_code": "J45.x (ربو) / J18.9 / I50.9 / J44.1 ...",
        "category": "أعراض — لا يُستخدم كتشخيص رئيسي",
        "requires_cb": [],
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# CPT codes reference
# ─────────────────────────────────────────────────────────────────────────────
CPT_DATABASE = {
    # E/M Office visits
    "99202": "زيارة مريض جديد — مشكلة بسيطة",
    "99203": "زيارة مريض جديد — مشكلة منخفضة التعقيد",
    "99204": "زيارة مريض جديد — مشكلة متوسطة التعقيد",
    "99205": "زيارة مريض جديد — مشكلة عالية التعقيد",
    "99211": "زيارة مريض متابعة — لا يحتاج طبيباً (ممرض)",
    "99212": "زيارة مريض متابعة — مشكلة بسيطة جداً",
    "99213": "زيارة مريض متابعة — مشكلة منخفضة التعقيد (الأكثر شيوعاً)",
    "99214": "زيارة مريض متابعة — مشكلة متوسطة التعقيد",
    "99215": "زيارة مريض متابعة — مشكلة عالية التعقيد",
    # ER
    "99281": "طوارئ — مشكلة بسيطة جداً",
    "99282": "طوارئ — مشكلة منخفضة",
    "99283": "طوارئ — مشكلة متوسطة",
    "99284": "طوارئ — مشكلة متوسطة-عالية",
    "99285": "طوارئ — مشكلة عالية التعقيد",
    # Preventive
    "99395": "فحص دوري — 18-39 سنة",
    "99396": "فحص دوري — 40-64 سنة",
    "99397": "فحص دوري — 65+ سنة",
    # Procedures
    "43239": "تنظير معدة مع خزعة",
    "45378": "تنظير القولون",
    "47562": "استئصال المرارة بالمنظار",
    "58150": "استئصال الرحم البطني الكلي",
    "76705": "سونار البطن",
    "76801": "سونار الحمل الثلث الأول",
    "76805": "سونار الحمل الكامل",
    # Radiology
    "71046": "صورة أشعة الصدر — وجهتان",
    "71045": "صورة أشعة الصدر — وجهة واحدة",
    "72148": "MRI العمود الفقري القطني",
    "72052": "أشعة العمود الفقري القطني",
    "70553": "MRI الدماغ مع تباين",
    "70486": "CT الجيوب الأنفية",
    "73562": "أشعة الركبة — وجهتان",
    "73564": "أشعة الركبة — أربع وجهات",
    "73221": "MRI الكتف",
    # Cardiology
    "93000": "تخطيط القلب الكهربائي (ECG) مع تفسير",
    "93005": "تخطيط القلب الكهربائي (ECG) فقط",
    "93224": "هولتر 24 ساعة",
    "93306": "إيكو القلب مع دوبلر",
    # Respiratory
    "94010": "قياس وظائف الرئة",
    "94640": "علاج تنفسي بالبخاخ (نبيولايزر)",
    "94664": "تعليم استخدام البخاخ",
    # Lab
    "80047": "فحوصات الأيض الأساسية (BMP)",
    "80053": "فحوصات الأيض الشاملة (CMP)",
    "80061": "لوحة الشحوم (Lipid Panel)",
    "81001": "فحص البول الشامل (U/A مع مجهر)",
    "81003": "فحص البول (U/A بدون مجهر)",
    "82465": "الكوليسترول الكلي",
    "82947": "جلوكوز الدم",
    "83036": "HbA1c",
    "83037": "HbA1c (نقطة رعاية)",
    "86580": "اختبار السل الجلدي",
    "87086": "زراعة البول",
    # Therapy
    "97110": "علاج طبيعي — تقوية عضلات",
    "97012": "علاج طبيعي — شد ميكانيكي",
    "99401": "إرشاد وقائي — 15 دقيقة",
    "90837": "جلسة علاج نفسي — 60 دقيقة",
    "90834": "جلسة علاج نفسي — 45 دقيقة",
    "92552": "قياس سمع نقي",
}

# ─────────────────────────────────────────────────────────────────────────────
# Common wrong CPT → correct CPT mapping (frequent mistakes)
# ─────────────────────────────────────────────────────────────────────────────
CPT_COMMON_MISTAKES = {
    "99232": {
        "description": "متابعة مريض منوم — يُستخدم خطأً بدلاً من 99213 للخارجي",
        "correct": ["99213","99214"],
    },
    "99231": {
        "description": "متابعة مريض منوم بسيطة — لا يصح للخارجي",
        "correct": ["99212","99213"],
    },
    "99285": {
        "description": "طوارئ معقدة — يُستخدم خطأً للزيارة الاعتيادية",
        "correct": ["99213","99214"],
    },
    "80053": {
        "description": "CMP — يُستخدم بدلاً من 80047 (BMP) أو 83036 (HbA1c)",
        "correct": ["80047","83036"],
    },
    "71045": {
        "description": "صورة صدر وجهة واحدة — أغلب التأمينات تطلب 71046 (وجهتان)",
        "correct": ["71046"],
    },
}
